# Generated by Django 4.1.1 on 2022-09-11 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=70)),
                ("page_cat", models.CharField(max_length=70)),
                ("favourite", models.BooleanField(default=False)),
                ("page_publish_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "connect",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relationproject.page",
                    ),
                ),
                ("count", models.IntegerField()),
            ],
            bases=("relationproject.page",),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=70)),
                ("post_cat", models.CharField(max_length=70)),
                ("post_publish_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="relationproject.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="page",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="relationproject.user"
            ),
        ),
        migrations.CreateModel(
            name="Nasheed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nasheed_name", models.CharField(max_length=70)),
                ("nasheed_duration", models.DurationField(null=True)),
                ("user", models.ManyToManyField(to="relationproject.user")),
            ],
        ),
    ]
