# Generated by Django 4.1.1 on 2022-09-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geeksmodel",
            name="description",
            field=models.TextField(max_length=100),
        ),
    ]
