# Generated by Django 4.1.1 on 2022-09-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modelrelation", "0002_alter_page_favourite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "connect",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="modelrelation.page",
                    ),
                ),
                ("count", models.IntegerField()),
            ],
            bases=("modelrelation.page",),
        ),
    ]
