# Generated by Django 4.1.1 on 2022-09-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelrelation", "0005_alter_post_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nasheed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nasheed_name", models.CharField(max_length=70)),
                ("nasheed_duration", models.DurationField(null=True)),
                ("user", models.ManyToManyField(to="modelrelation.user")),
            ],
        ),
    ]
